version: '3.5'
services:
  benchmark-test:
    build:
      context: ../..
      dockerfile: buildkite/benchmark-test/Dockerfile
    environment:
      BENCHMARKABLE: ${BENCHMARKABLE:-641554b0bcce587549bfcfd0cde3cb4bc23054aa}
      BENCHMARKABLE_TYPE: ${BENCHMARKABLE_TYPE:-arrow-commit}
      BENCHMARKS_DATA_DIR: "/data"
      CONBENCH_CLI: ${CONBENCH_CLI:-conbench-v2}
      CONBENCH_TOKEN: ${CONBENCH_TOKEN}
      CONBENCH_URL: "https://conbench.arrow-dev.org"
      FILTERS: "${FILTERS:-{}}"
      MACHINE: "docker-container-for-testing-benchmark-builds"
      PYTHON_VERSION: ${PYTHON_VERSION:-3.12}
      RUN_ID: ${BUILDKITE_BUILD_ID}
      RUN_NAME: "benchmark build test: ${BUILDKITE_BUILD_ID}"
